export const placementInstruments = ["clarinet", "flute", "piccolo", "oboe", "english_horn", "bassoon", "french_horn", "trumpet", "trombone", "tuba", "soprano_sax", "alto_sax", "tenor_sax", "baritone_sax", "violin", "viola", "cello", "contrabass", "acoustic_bass", "string_ensemble_1", "synth_strings_1", "synth_strings_2", "orchestral_harp", "timpani", "marimba", "glockenspiel", "harpsichord", "acoustic_guitar_nylon", "acoustic_grand_piano", "electric_piano_1", "electric_piano_2", "church_organ", "rock_organ", "choir_aahs"] as const;

export const instrumentLabels: Record<string, string> = { clarinet: "クラリネット", flute: "フルート", piccolo: "ピッコロ", oboe: "オーボエ", english_horn: "イングリッシュホルン", bassoon: "ファゴット", french_horn: "ホルン", trumpet: "トランペット", trombone: "トロンボーン", tuba: "チューバ", soprano_sax: "ソプラノサックス", alto_sax: "アルトサックス", tenor_sax: "テナーサックス", baritone_sax: "バリトンサックス", violin: "ヴァイオリン", viola: "ヴィオラ", cello: "チェロ", contrabass: "コントラバス", acoustic_bass: "アコースティックベース", string_ensemble_1: "弦楽合奏", synth_strings_1: "シンセ弦1", synth_strings_2: "シンセ弦2", orchestral_harp: "ハープ", timpani: "ティンパニ", marimba: "マリンバ", glockenspiel: "グロッケンシュピール", harpsichord: "チェンバロ", acoustic_guitar_nylon: "クラシックギター", acoustic_grand_piano: "ピアノ", electric_piano_1: "エレクトリックピアノ1", electric_piano_2: "エレクトリックピアノ2", church_organ: "パイプオルガン", rock_organ: "ロックオルガン", choir_aahs: "合唱" };

export const instrumentLabelsEn: Record<(typeof placementInstruments)[number], string> = { clarinet: "Clarinet", flute: "Flute", piccolo: "Piccolo", oboe: "Oboe", english_horn: "English horn", bassoon: "Bassoon", french_horn: "French horn", trumpet: "Trumpet", trombone: "Trombone", tuba: "Tuba", soprano_sax: "Soprano saxophone", alto_sax: "Alto saxophone", tenor_sax: "Tenor saxophone", baritone_sax: "Baritone saxophone", violin: "Violin", viola: "Viola", cello: "Cello", contrabass: "Double bass", acoustic_bass: "Acoustic bass", string_ensemble_1: "String ensemble", synth_strings_1: "Synth strings 1", synth_strings_2: "Synth strings 2", orchestral_harp: "Harp", timpani: "Timpani", marimba: "Marimba", glockenspiel: "Glockenspiel", harpsichord: "Harpsichord", acoustic_guitar_nylon: "Classical guitar", acoustic_grand_piano: "Piano", electric_piano_1: "Electric piano 1", electric_piano_2: "Electric piano 2", church_organ: "Pipe organ", rock_organ: "Rock organ", choir_aahs: "Choir" };

export const instrumentGroups = [["木管", ["flute", "piccolo", "oboe", "english_horn", "bassoon", "clarinet", "soprano_sax", "alto_sax", "tenor_sax", "baritone_sax"]], ["金管", ["french_horn", "trumpet", "trombone", "tuba"]], ["弦", ["violin", "viola", "cello", "contrabass", "acoustic_bass", "string_ensemble_1", "synth_strings_1", "synth_strings_2", "orchestral_harp"]], ["鍵盤・打楽器", ["acoustic_grand_piano", "electric_piano_1", "electric_piano_2", "church_organ", "rock_organ", "harpsichord", "acoustic_guitar_nylon", "timpani", "marimba", "glockenspiel", "choir_aahs"]]] as const;

export const instrumentGroupLabelsEn: Record<(typeof instrumentGroups)[number][0], string> = { 木管: "Woodwinds", 金管: "Brass", 弦: "Strings", "鍵盤・打楽器": "Keyboards & percussion" };
