/**
 * Score loader with pre-parsed JSON support.
 *
 * Tries to load a `.score.json` file first (generated by convert_score.py).
 * Falls back to the client-side MusicXML parser if the JSON is unavailable.
 */

import type { ParsedScore } from "./types";
import { parseMusicXML } from "./musicxml-parser";

interface ScoreJsonNote {
  pitch: number;
  startBeat: number;
  durationBeats: number;
  velocity: number;
  partIndex: number;
}

interface ScoreJsonPart {
  id: string;
  name: string;
  isSolo: boolean;
  notes: ScoreJsonNote[];
}

interface ScoreJsonExpression {
  beat_period: number[];
  velocity: number[];
  timing: number[];
  articulation_log: number[];
}

interface ScoreJson {
  title: string;
  tempo: number;
  timeSignature: { beats: number; beatType: number };
  parts: ScoreJsonPart[];
  measures: ParsedScore["measures"];
  totalMeasures: number;
  totalBeats: number;
  playbackOrder: number[];
  measureNumbers: number[];
  tempoEvents?: ParsedScore["measures"];
  expressionParams?: ScoreJsonExpression;
}

function jsonToMusicXMLPath(jsonPath: string): string {
  return jsonPath.replace(/\.score\.json$/, ".musicxml");
}

function musicXMLToJsonPath(xmlPath: string): string {
  return xmlPath.replace(/\.(musicxml|xml|mxl)$/, ".score.json");
}

/**
 * Load a score from the given path.
 * If a `.score.json` exists alongside the MusicXML, uses that for better accuracy.
 * Returns both the ParsedScore and the raw MusicXML string (needed for OSMD rendering).
 */
export async function loadScore(
  path: string
): Promise<{ score: ParsedScore; musicXML: string }> {
  const jsonPath = path.endsWith(".score.json")
    ? path
    : musicXMLToJsonPath(path);
  const xmlPath = path.endsWith(".score.json")
    ? jsonToMusicXMLPath(path)
    : path;

  const [jsonResult, xmlResult] = await Promise.allSettled([
    fetch(jsonPath).then((r) => {
      if (!r.ok) throw new Error(`${r.status}`);
      return r.json() as Promise<ScoreJson>;
    }),
    fetch(xmlPath).then((r) => {
      if (!r.ok) throw new Error(`${r.status}`);
      return r.text();
    }),
  ]);

  const musicXML =
    xmlResult.status === "fulfilled" ? xmlResult.value : null;
  const scoreJson =
    jsonResult.status === "fulfilled" ? jsonResult.value : null;

  if (scoreJson && musicXML) {
    const score: ParsedScore = {
      title: scoreJson.title,
      tempo: scoreJson.tempo,
      timeSignature: scoreJson.timeSignature,
      parts: scoreJson.parts,
      measures: scoreJson.measures ?? [],
      totalMeasures: scoreJson.totalMeasures,
      totalBeats: scoreJson.totalBeats,
      playbackOrder: scoreJson.playbackOrder,
      measureNumbers: scoreJson.measureNumbers,
    };
    if (scoreJson.expressionParams) {
      score.expressionParams = {
        beatPeriod: scoreJson.expressionParams.beat_period,
        velocity: scoreJson.expressionParams.velocity,
        timing: scoreJson.expressionParams.timing,
        articulationLog: scoreJson.expressionParams.articulation_log,
      };
    }
    return { score, musicXML };
  }

  if (musicXML) {
    return { score: parseMusicXML(musicXML), musicXML };
  }

  throw new Error(`Failed to load score from ${path}`);
}

/**
 * Parse a MusicXML string directly (for file uploads where no JSON exists).
 */
export function parseUploadedScore(xmlString: string): ParsedScore {
  return parseMusicXML(xmlString);
}
