import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";

test("saved take reopens after reload for comparison without changing settings or starting playback", async ({ page }) => {
  const load = async () => {
    await page.getByLabel("MusicXMLで演奏する", { exact: true }).setInputFiles("public/scores/sample-duet.musicxml");
    await expect(page.getByRole("button", { name: "テイクを記録して演奏", exact: true })).toBeEnabled();
  };
  await page.goto("/perform"); await load();
  await page.getByLabel("楽譜への追従方式").selectOption("sequence");
  await page.getByRole("button", { name: "テイクを記録して演奏", exact: true }).click();
  await expect(page.getByLabel("保存したテイクを開く")).toBeDisabled();
  await page.getByRole("button", { name: "テイクを終了", exact: true }).click();
  await page.getByText("次の練習のためにメモを残す（任意）", { exact: true }).click();
  await page.getByLabel("テイク 1 の練習メモ").fill("息継ぎ後の入りを試す");
  const downloading = page.waitForEvent("download");
  await page.getByRole("button", { name: "テイクの記録を保存", exact: true }).click();
  const download = await downloading;
  const buffer = readFileSync((await download.path())!);
  await page.reload(); await load();
  await page.getByLabel("楽譜への追従方式").selectOption("nearest");
  const upload = (data: Buffer) => page.getByLabel("保存したテイクを開く").setInputFiles({ name: "take.json", mimeType: "application/json", buffer: data });
  await upload(buffer);
  await expect(page.getByText("テイクと感想を開きました。", { exact: false })).toBeVisible();
  await expect(page.getByLabel("楽譜への追従方式")).toHaveValue("nearest");
  await expect(page.locator(".status-pill")).toContainText("準備完了");
  await page.getByText("次の練習のためにメモを残す（任意）", { exact: true }).click();
  await expect(page.getByLabel("テイク 1 の練習メモ")).toHaveValue("息継ぎ後の入りを試す");
  await expect(page.getByLabel("テイク 1 の再利用意向")).toHaveValue("");
  await page.getByRole("button", { name: "同じ入力でA/B比較", exact: true }).click();
  await expect(page.getByRole("table").filter({ hasText: "同一入力の応答比較" })).toBeVisible();
  await upload(buffer);
  await expect(page.getByRole("button", { name: "同じ入力でA/B比較", exact: true })).toHaveCount(1);
  await upload(Buffer.from("{}"));
  await expect(page.getByText("テイクの記録が不正です。", { exact: false })).toBeVisible();
  await expect(page.getByLabel("テイク 1 の練習メモ")).toHaveValue("息継ぎ後の入りを試す");
  await upload(Buffer.from(JSON.stringify({ ...JSON.parse(buffer.toString()), seatId: "other" })));
  await expect(page.getByText("保存時と同じ譜面・移調・担当", { exact: false })).toBeVisible();
  const changedContext = { ...JSON.parse(buffer.toString()), scoreContext: "score-v1:wrong" };
  await upload(Buffer.from(JSON.stringify(changedContext)));
  await expect(page.getByText("テイクと楽譜の演奏条件が違います。", { exact: false })).toBeVisible();
  const legacy = JSON.parse(buffer.toString());
  delete legacy.scoreContext;
  await upload(Buffer.from(JSON.stringify(legacy)));
  await expect(page.getByRole("button", { name: "同じ入力でA/B比較", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "このテイクの表現で共奏する", exact: true })).toBeDisabled();
  await expect(page.getByLabel("テイク 1 の練習メモ")).toHaveValue("息継ぎ後の入りを試す");
  await upload(buffer);
  await expect(page.getByRole("button", { name: "同じ入力でA/B比較", exact: true })).toBeEnabled();
});
