void (async () => {
  const wait = async (read, description) => {
    webkit.messageHandlers.testResult.postMessage({progress:description});
    const deadline = performance.now() + 30000;
    while (performance.now() < deadline) { const value = read(); if (value) return value; await new Promise(resolve => setTimeout(resolve, 100)); }
    throw new Error(`Timed out: ${description}; ${JSON.stringify({ status:document.querySelector('.status-pill')?.textContent, seat:document.querySelector('[aria-label="奏者パート"]')?.value, notes:[...document.querySelectorAll('.printable-score [data-score-beat]')].slice(0,8).map(note => ({voice:note.dataset.scoreVoice, staff:note.dataset.scoreStaff, focused:note.dataset.scoreFocused, current:note.classList.contains('score-current-note')})) })}`);
  };
  try {
    const errors = [];
    for (const style of ['400 16px Inter','italic 700 16px Inter']) {
      const fonts=await document.fonts.load(style,'ConvoCerto');
      if (!fonts.length || fonts.some(font=>font.status!=='loaded')) throw new Error('Bundled Inter font failed to load');
    }
    const fontResponse=await fetch('/fonts/inter/InterVariable.woff2');
    if (!fontResponse.ok || !fontResponse.headers.get('content-type')?.includes('font/woff2')) throw new Error('Native font MIME type missing');
    for (const [path, expected] of [['/credits.html', 'Frank Wen'], ['/notices/dependencies.html', 'Permission is hereby granted']]) {
      const resource = await fetch(path);
      if (!resource.ok || !resource.headers.get('content-type')?.includes('text/html') || !(await resource.text()).includes(expected)) throw new Error('Bundled notices missing: ' + path);
    }
    const bundledNotices = await (await fetch('/notices/bundled-packages.json')).json();
    if (!bundledNotices.packages.some(item => item.name === 'react' && item.noticeStatus === 'text-collected') || bundledNotices.commercialClearance !== false) throw new Error('Bundled package audit missing');
    let printResult;
    addEventListener("convocerto-print", event => { printResult = event.detail; });
    let sourceStarts = 0;
    let loopedStarts = 0;
    let playbackContext;
    const start = AudioBufferSourceNode.prototype.start;
    AudioBufferSourceNode.prototype.start = function (...args) { sourceStarts++; if (this.loop) loopedStarts++; playbackContext = this.context; return start.apply(this, args); };
    addEventListener('error', event => errors.push(event.message));
    const input = await wait(() => document.querySelector('input[accept*=".mxl"]'), 'React input');
    await wait(() => document.querySelector('article.piano')?.textContent.includes('配布版には含めていません'), 'unbundled Brahms availability notice');
    if ([...document.querySelectorAll('article.piano .movement-list button')].some(button => !button.disabled)) throw new Error('Unbundled repertoire is selectable');
    const response = await fetch('/repertoire/ensemble/mozart-k622-2.musicxml');
    if (!response.ok) throw new Error('Bundled Mozart missing');
    const xml = await response.text();
    const transfer = new DataTransfer();
    transfer.items.add(new File([xml], 'mozart.musicxml', {type:'application/xml'}));
    input.files = transfer.files; input.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => [...document.querySelectorAll('button')].find(button => button.textContent === '▶ 演奏開始' && !button.disabled), 'score and instrument samples');
    await wait(() => document.querySelector('.printable-score svg'), 'engraved score');
    const controls = [...document.querySelectorAll('button')];
    document.querySelector('.part-row button').click();
    await wait(() => document.querySelector('.part-row button').getAttribute('aria-pressed') === 'true', 'mute accompaniment');
    controls.find(button => button.textContent === 'この練習を保存').click();
    await wait(() => document.querySelector('[aria-label="マイ楽譜"] button[aria-label$="をマイ楽譜から削除"]'), 'IndexedDB persistence');
    document.querySelector('.part-row button').click();
    await wait(() => document.querySelector('.part-row button').getAttribute('aria-pressed') === 'false', 'unmute before restore');
    document.querySelector('[aria-label="マイ楽譜"] button[aria-label$="をマイ楽譜から削除"]').parentElement.querySelector('button').click();
    await wait(() => document.querySelector('.part-row button')?.getAttribute('aria-pressed') === 'true', 'restore saved mute');
    await wait(() => [...document.querySelectorAll('button')].find(button => button.textContent === '▶ 演奏開始' && !button.disabled), 'restored instruments');
    [...document.querySelectorAll('button')].find(button => button.textContent === '楽譜専用ページで演奏する →').click();
    await wait(() => document.querySelector('.score-page'), 'score view');
    if ((await fetch('/not-a-real-file.musicxml')).status !== 404) throw new Error('Missing asset must be 404');
    [...document.querySelectorAll('button')].find(button => button.textContent === '▶ 演奏開始').click();
    await wait(() => Number(document.querySelector('[aria-label="演奏位置"]').value) > 0 && sourceStarts > 0, 'Web Audio playback');
    [...document.querySelectorAll('button')].find(button => button.textContent === 'この小節から入り直す').click();
    await wait(() => document.querySelector('.status-pill')?.textContent.includes('カウントイン'), 'rejoin count-in');
    const rejoinBeat = Number(document.querySelector('[aria-label="演奏位置"]').value);
    await new Promise(resolve => setTimeout(resolve, 300));
    if (Number(document.querySelector('[aria-label="演奏位置"]').value) !== rejoinBeat) throw new Error('Rejoin advanced during count-in');
    await wait(() => Number(document.querySelector('[aria-label="演奏位置"]').value) > rejoinBeat, 'rejoin transport after count-in');
    [...document.querySelectorAll('button')].find(button => button.textContent === '■ 停止').click();
    const countInSelector = await wait(() => { const select = document.querySelector('[aria-label="カウントイン"]'); return select && !select.disabled ? select : null; }, 'count-in selector after stop');
    countInSelector.value = '0'; countInSelector.dispatchEvent(new Event('change', {bubbles:true}));
    [...document.querySelectorAll('button')].find(button => button.textContent === '▶ 演奏開始').click();
    await wait(() => Number(document.querySelector('[aria-label="演奏位置"]').value) > 0, 'transport after rejoin verification');
    await playbackContext.suspend();
    const recover = await wait(() => [...document.querySelectorAll('button')].find(button => button.textContent === '音声を復旧して再開'), 'audio interruption notice');
    const heldBeat = Number(document.querySelector('[aria-label="演奏位置"]').value);
    await playbackContext.resume();
    await new Promise(resolve => setTimeout(resolve, 300));
    if (Number(document.querySelector('[aria-label="演奏位置"]').value) !== heldBeat) throw new Error('Interrupted transport resumed without user action');
    await playbackContext.suspend();
    const startsBeforeRecovery = sourceStarts;
    recover.click();
    await wait(() => Number(document.querySelector('[aria-label="演奏位置"]').value) > heldBeat && sourceStarts > startsBeforeRecovery, 'audio and transport recovery');
    const frozenClock = playbackContext.currentTime;
    Object.defineProperty(playbackContext,'currentTime',{configurable:true,get:()=>frozenClock});
    const clockRecovery = await wait(()=>[...document.querySelectorAll('button')].find(button=>button.textContent==='音声を復旧して再開'),'frozen running audio clock recovery');
    const frozenBeat = Number(document.querySelector('[aria-label="演奏位置"]').value);
    delete playbackContext.currentTime;
    await new Promise(resolve=>setTimeout(resolve,300));
    if (Number(document.querySelector('[aria-label="演奏位置"]').value)!==frozenBeat) throw new Error('Frozen clock recovery autoplayed');
    clockRecovery.click();
    await wait(()=>Number(document.querySelector('[aria-label="演奏位置"]').value)>frozenBeat,'explicit frozen clock resume');
    [...document.querySelectorAll('button')].find(button => button.textContent === '■ 停止').click();
    if (Number(document.querySelector('[aria-label="演奏位置"]').value) !== 0) await wait(() => Number(document.querySelector('[aria-label="演奏位置"]').value) === 0, 'stop');
    const printedPages = document.querySelectorAll('.printable-score svg').length;
    [...document.querySelectorAll('button')].find(button => button.textContent === '楽譜を印刷 / PDF').click();
    await wait(() => printResult, 'native print operation');
    if (printResult.status !== 'completed' || printResult.pages !== printedPages) throw new Error('Native print failed: ' + JSON.stringify({printResult,printedPages}));
    const connect = [...document.querySelectorAll('button')].find(button => button.textContent === '準備・オーケストラ');
    connect.click();
    [...document.querySelectorAll('button')].find(button => button.textContent === 'ClariMate / MIDIを接続').click();
    const deviceSelector = document.querySelector('[aria-label="MIDI機器"]');
    const chooseTest = async () => {
      const option = await wait(() => [...deviceSelector.options].filter(option => option.textContent.includes('ConvoCerto Test Input')).at(-1), 'CoreMIDI test source');
      deviceSelector.value = option.value; deviceSelector.dispatchEvent(new Event('change', {bubbles:true}));
      return option.value;
    };
    const firstID = await chooseTest();
    const monitorButton = () => [...document.querySelectorAll('button')].find(button => button.textContent.startsWith('MIDI入力の試聴（電子音）'));
    monitorButton().click();
    await wait(() => monitorButton().getAttribute('aria-pressed') === 'true', 'MIDI monitor audio ready');
    webkit.messageHandlers.convoMIDI.postMessage({action:'test-send',data:[0x90,72,85,0xb0,11,96]});
    await wait(() => document.querySelector('.midi-reading').textContent.includes('強さ 85'), 'CoreMIDI note to React');
    await wait(() => document.querySelector('[aria-label="ClariMateの息"]').value === 96, 'CoreMIDI CC11');
    const originalGainRamp = AudioParam.prototype.linearRampToValueAtTime;
    const monitorRamps = [];
    AudioParam.prototype.linearRampToValueAtTime = function (value, time) { monitorRamps.push(value); return originalGainRamp.call(this, value, time); };
    try {
      webkit.messageHandlers.convoMIDI.postMessage({action:'test-send',data:[0xb0,11,32]});
      await wait(() => monitorRamps.some(value => Math.abs(value - 32 / 127) < 0.0001), 'CoreMIDI expression changes monitor gain');
      monitorRamps.length = 0;
      webkit.messageHandlers.convoMIDI.postMessage({action:'test-send',data:[0xb0,2,0]});
      await wait(() => monitorRamps.includes(0), 'CoreMIDI zero breath silences monitor gain');
    } finally { AudioParam.prototype.linearRampToValueAtTime = originalGainRamp; }
    monitorButton().click();
    await wait(() => monitorButton().getAttribute('aria-pressed') === 'false', 'MIDI monitor stopped');
    [...document.querySelectorAll('button')].find(button => button.textContent === '▶ 演奏開始').click();
    await wait(() => Number(document.querySelector('[aria-label="演奏位置"]').value) > 0, 'transport before MIDI disconnect');
    webkit.messageHandlers.convoMIDI.postMessage({action:'test-disconnect'});
    await wait(() => ![...deviceSelector.options].some(option => option.value === firstID) && deviceSelector.value === '', 'device disconnection');
    await wait(() => ![...document.querySelectorAll('button')].some(button => button.textContent === '■ 停止'), 'MIDI disconnection pauses transport');
    const midiHeldBeat = Number(document.querySelector('[aria-label="演奏位置"]').value);
    if (midiHeldBeat <= 0) throw new Error('MIDI disconnection lost position');
    webkit.messageHandlers.convoMIDI.postMessage({action:'test-reconnect'});
    await chooseTest();
    webkit.messageHandlers.convoMIDI.postMessage({action:'test-send',packets:[[0x90,60],[71,0xf8,61,72]]});
    await wait(() => document.querySelector('.midi-reading').textContent.includes('強さ 72'), 'reconnection and running status');
    if (Number(document.querySelector('[aria-label="演奏位置"]').value) !== midiHeldBeat) throw new Error('MIDI reconnect resumed automatically');
    [...document.querySelectorAll('button')].find(button => button.textContent === '▶ 演奏開始').click();
    await wait(() => Number(document.querySelector('[aria-label="演奏位置"]').value) > midiHeldBeat, 'resume after MIDI reconnect');
    [...document.querySelectorAll('button')].find(button => button.textContent === '■ 停止').click();
    const downloads = [];
    addEventListener('convocerto-download', event => downloads.push(event.detail));
    let exportedBlob;
    const objectURL = URL.createObjectURL;
    URL.createObjectURL = function (blob) { exportedBlob = blob; return objectURL.call(this, blob); };
    const verifyExport = async (label, filename) => {
      const before = downloads.length;
      const button = [...document.querySelectorAll('button')].find(button => button.textContent === label);
      if (!button) throw new Error(`Missing export: ${label}`);
      button.click();
      const bytes = await exportedBlob.arrayBuffer();
      const digest = [...new Uint8Array(await crypto.subtle.digest('SHA-256', bytes))].map(byte => byte.toString(16).padStart(2,'0')).join('');
      const result = await wait(() => downloads[before], 'native file export');
      if (result.status !== 'saved' || result.sha256 !== digest || result.name !== filename) throw new Error(`Export mismatch: ${JSON.stringify(result)}`);
      return new TextDecoder().decode(bytes);
    };
    const exportedXML = await verifyExport('指示付きMusicXMLを保存', 'rehearsal.musicxml');
    if (!exportedXML.includes('score-partwise')) throw new Error('Exported XML has no score');
    const currentPractice = await verifyExport('今の練習をファイルに書き出す', 'practice.convo.json');
    if (JSON.parse(currentPractice).score.session.mutedPartIds?.length !== 1) throw new Error('Current practice export lost mute');
    const exportedPractice = await verifyExport('練習ファイルを書き出す', 'practice.convo.json');
    if (JSON.parse(exportedPractice).score.session.mutedPartIds?.length !== 1) throw new Error('Exported practice lost mute');
    if (JSON.parse(exportedPractice).format !== 'convocerto-practice') throw new Error('Practice envelope missing');
    const originalOpen = IDBFactory.prototype.open;
    try {
      IDBFactory.prototype.open = function (name, ...args) {
        if (name === 'convocerto-library') throw new DOMException('Test storage unavailable', 'SecurityError');
        return originalOpen.call(this, name, ...args);
      };
      const practiceTransfer = new DataTransfer();
      practiceTransfer.items.add(new File([currentPractice], 'backup.convo.json', {type:'application/json'}));
      const practiceInput = document.querySelector('input[aria-label="練習ファイルを読み込む"]');
      practiceInput.files = practiceTransfer.files; practiceInput.dispatchEvent(new Event('change', {bubbles:true}));
      const openUnsaved = await wait(() => [...document.querySelectorAll('button')].find(button => button.textContent === '保存せず、この練習を開く'), 'storage-independent practice import');
      openUnsaved.click();
      await wait(() => [...document.querySelectorAll('button')].find(button => button.textContent === '▶ 演奏開始' && !button.disabled), 'unsaved practice ready');
      await wait(() => document.querySelector('.part-row button')?.getAttribute('aria-pressed') === 'true', 'unsaved practice mute');
      if ([...document.querySelectorAll('button')].some(button => button.textContent === '■ 停止')) throw new Error('Unsaved practice started automatically');
    } finally { IDBFactory.prototype.open = originalOpen; }
    const originalMicrophone = navigator.mediaDevices.getUserMedia;
    const originalMicrophoneList = navigator.mediaDevices.enumerateDevices;
    let simulatedMicrophone;
    let simulatedTrack;
    try {
      const repeatedXML = `<score-partwise version="4.0"><work><work-title>Repeated microphone notes</work-title></work><part-list><score-part id="P1"><part-name>Clarinet</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>${Array.from({length:4}, () => '<note><pitch><step>A</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type><notations><fermata/></notations></note>').join('')}</measure></part></score-partwise>`;
      const repeatedTransfer = new DataTransfer();
      repeatedTransfer.items.add(new File([repeatedXML], 'repeated.musicxml', {type:'application/xml'}));
      const repeatedInput = document.querySelector('input[accept*=".mxl"]');
      repeatedInput.files = repeatedTransfer.files; repeatedInput.dispatchEvent(new Event('change', {bubbles:true}));
      await wait(() => document.body.textContent.includes('Repeated microphone notes') && [...document.querySelectorAll('button')].some(button => button.textContent === '▶ 演奏開始' && !button.disabled), 'repeated-note score ready');
      if (!document.querySelector('.playback-issues')?.textContent.includes('フェルマータ · 4件')) throw new Error('MusicXML playback limitations missing');
      const repeatedMode = document.querySelector('[aria-label="練習モード"]');
      repeatedMode.value = 'wait'; repeatedMode.dispatchEvent(new Event('change', {bubbles:true}));
      let repeatedSource;
      navigator.mediaDevices.enumerateDevices = async () => [{kind:'audioinput', deviceId:'native-test-mic', label:'Native Test Microphone'}];
      [...document.querySelectorAll('button')].find(button => button.textContent === 'マイク一覧を更新').click();
      await wait(() => document.querySelector('[aria-label="使用するマイク"] option[value="native-test-mic"]'), 'microphone device list');
      const microphoneSelector = document.querySelector('[aria-label="使用するマイク"]');
      microphoneSelector.value = 'native-test-mic'; microphoneSelector.dispatchEvent(new Event('change', {bubbles:true}));
      navigator.mediaDevices.getUserMedia = async (constraints) => {
        if (constraints.audio.deviceId?.exact !== 'native-test-mic') throw new Error('Selected microphone constraint missing');
        simulatedMicrophone = new AudioContext(); await simulatedMicrophone.resume();
        const destination = simulatedMicrophone.createMediaStreamDestination();
        repeatedSource = simulatedMicrophone.createBufferSource();
        const buffer = simulatedMicrophone.createBuffer(1, Math.ceil(simulatedMicrophone.sampleRate * 1.2), simulatedMicrophone.sampleRate);
        const samples = buffer.getChannelData(0);
        for (let i = 0; i < samples.length; i++) {
          const seconds = i / simulatedMicrophone.sampleRate;
          const phase = 2 * Math.PI * 440 * seconds;
          samples[i] = seconds % 0.3 < 0.26 ? 0.2 * Math.sin(phase) + 0.08 * Math.sin(3 * phase) : 0;
        }
        repeatedSource.buffer = buffer; repeatedSource.connect(destination);
        simulatedTrack = destination.stream.getAudioTracks()[0];
        Object.defineProperty(simulatedTrack, 'label', {value:'Native Test Microphone'});
        return destination.stream;
      };
      [...document.querySelectorAll('button')].find(button => button.textContent === 'マイクで演奏する').click();
      await wait(() => [...document.querySelectorAll('button')].find(button => button.textContent === 'マイクを停止'), 'simulated microphone connected');
      if (!microphoneSelector.disabled || !document.body.textContent.includes('使用中のマイク: Native Test Microphone')) throw new Error('Active microphone selection or label incorrect');
      [...document.querySelectorAll('button')].find(button => button.textContent === '▶ 演奏開始').click();
      await wait(() => document.querySelector('.status-pill')?.textContent === '正しい音を待っています', 'waiting for repeated microphone notes');
      repeatedSource.start();
      await wait(() => document.querySelector('.status-pill')?.textContent === '演奏終了', 'four repeated microphone notes advance the score');
      if (Number(document.querySelector('[aria-label="演奏位置"]').value) !== 4) throw new Error('Repeated microphone notes lost score position');
      simulatedTrack.stop(); simulatedTrack.dispatchEvent(new Event('ended'));
      await wait(() => [...document.querySelectorAll('[role="alert"]')].some(node => node.textContent.includes('マイク入力が中断しました')), 'microphone disconnection notice');
      if (![...document.querySelectorAll('button')].some(button => button.textContent === 'マイクで演奏する')) throw new Error('Microphone did not return to disconnected state');
      if (microphoneSelector.disabled || microphoneSelector.value !== 'native-test-mic' || document.body.textContent.includes('使用中のマイク:')) throw new Error('Disconnected microphone selection was not retained');
    } finally { navigator.mediaDevices.getUserMedia = originalMicrophone; navigator.mediaDevices.enumerateDevices = originalMicrophoneList; if (simulatedMicrophone) await simulatedMicrophone.close(); }
    const voiceXML = `<score-partwise version="4.0"><work><work-title>Selected voice display</work-title></work><part-list><score-part id="C"><part-name>Clarinets</part-name></score-part></part-list><part id="C"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><note><pitch><step>C</step><octave>4</octave></pitch><duration>4</duration><voice>1</voice><type>whole</type></note><backup><duration>4</duration></backup><note><pitch><step>G</step><octave>4</octave></pitch><duration>4</duration><voice>2</voice><type>whole</type></note></measure></part></score-partwise>`.replace('<note>', '<direction><direction-type><dynamics><p/></dynamics><wedge type="crescendo"/></direction-type></direction><note>').replace('</measure>', '<direction><direction-type><wedge type="stop"/><dynamics><f/></dynamics></direction-type></direction></measure>').replaceAll('<duration>4</duration>', '<duration>8</duration>');
    const voiceTransfer = new DataTransfer();
    voiceTransfer.items.add(new File([voiceXML], 'voices.musicxml', {type:'application/xml'}));
    const voiceInput = document.querySelector('input[accept*=".mxl"]');
    voiceInput.files = voiceTransfer.files; voiceInput.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => document.body.textContent.includes('Selected voice display') && !document.querySelector('[aria-label="奏者パート"]').disabled, 'voice score ready');
    const voiceSelector = document.querySelector('[aria-label="奏者パート"]');
    voiceSelector.value = JSON.stringify(['C', '1', '2']); voiceSelector.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => document.querySelector('.printable-score [data-score-voice="2"][data-score-focused="true"]') && document.querySelector('.printable-score [data-score-voice="1"][opacity="0.35"]') && document.querySelector('.score-current-note[data-score-voice="2"]'), 'selected voice prominence');
    if (document.querySelectorAll('.score-current-note').length !== 1 || document.querySelector('.score-current-note').dataset.scoreVoice !== '2') throw new Error('Highlight includes another player voice');
    if (document.querySelector('.playback-issues')?.textContent.includes('フェルマータ')) throw new Error('Old MusicXML limitations persisted after another score loaded');
    const loopedBeforeHeldNote = loopedStarts;
    const hairpinRamps = new Map();
    const originalHairpinRamp = AudioParam.prototype.linearRampToValueAtTime;
    AudioParam.prototype.linearRampToValueAtTime = function(value,time) { const events=hairpinRamps.get(this) ?? []; events.push({value,time}); hairpinRamps.set(this,events); return originalHairpinRamp.call(this,value,time); };
    try {
      [...document.querySelectorAll('button')].find(button=>button.textContent==='▶ 演奏開始').click();
      await wait(()=>[...hairpinRamps.values()].some(events=>{const positive=events.filter(event=>event.value>0);return positive.length>1 && positive[1].value>positive[0].value*1.5 && positive[1].time-positive[0].time>0.3;}),'MusicXML hairpin schedules increasing sustained gain');
      if (loopedStarts <= loopedBeforeHeldNote) throw new Error('Long clarinet accompaniment did not use sustain loop');
      const beforeHeldSeek = sourceStarts;
      const heldSeek = document.querySelector('[aria-label="演奏位置"]');
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(heldSeek,'2');
      heldSeek.dispatchEvent(new Event('input',{bubbles:true}));
      heldSeek.dispatchEvent(new Event('change',{bubbles:true}));
      await wait(()=>sourceStarts>beforeHeldSeek,'held orchestra note resumes after seeking inside note');
      [...document.querySelectorAll('button')].find(button=>button.textContent==='■ 停止')?.click();
    } finally {AudioParam.prototype.linearRampToValueAtTime=originalHairpinRamp;}
    const startTake = await wait(()=>[...document.querySelectorAll('button')].find(button=>button.textContent==='テイクを記録して演奏' && !button.disabled),'take controls ready after stopping');
    startTake.click();
    const endTake = await wait(()=>[...document.querySelectorAll('button')].find(button=>button.textContent==='テイクを終了'),'take recording available');
    endTake.click();
    const reuse = await wait(()=>document.querySelector('[aria-label="テイク 1 の再利用意向"]'),'take experience form');
    reuse.closest('details').open = true;
    if (reuse.value !== '') throw new Error('Experience answer must not be preselected');
    reuse.value='unsure'; reuse.dispatchEvent(new Event('change',{bubbles:true}));
    const memo=document.querySelector('[aria-label="テイク 1 の練習メモ"]');
    Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(memo,'息継ぎの後をもう一度試す');
    memo.dispatchEvent(new Event('input',{bubbles:true}));
    await wait(()=>document.querySelector('[aria-label="テイク 1 の再利用意向"]').value==='unsure' && document.querySelector('[aria-label="テイク 1 の練習メモ"]').value==='息継ぎの後をもう一度試す','take experience retained during form editing');
    let takeBlob;
    const createTakeURL = URL.createObjectURL;
    const clickTakeLink = HTMLAnchorElement.prototype.click;
    try {
      URL.createObjectURL = function(blob) { takeBlob = blob; return createTakeURL.call(this, blob); };
      HTMLAnchorElement.prototype.click = function() { if (!this.download.startsWith('convo-take-')) clickTakeLink.call(this); };
      [...document.querySelectorAll('button')].find(button => button.textContent === 'テイクの記録を保存').click();
    } finally { URL.createObjectURL = createTakeURL; HTMLAnchorElement.prototype.click = clickTakeLink; }
    if (!takeBlob) throw new Error('Take export missing');
    const restoredTake = JSON.parse(await takeBlob.text());
    restoredTake.id = 'native-restored-take';
    const takeUpload = document.querySelector('[aria-label="保存したテイクを開く"]');
    const takeTransfer = new DataTransfer();
    takeTransfer.items.add(new File([JSON.stringify(restoredTake)], 'take.json', {type:'application/json'}));
    takeUpload.files = takeTransfer.files;
    takeUpload.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => document.querySelector('[aria-label="テイク 2 の練習メモ"]')?.value === '息継ぎの後をもう一度試す', 'saved take import restores notes in WKWebView');
    if (document.querySelector('[aria-label="テイク 2 の再利用意向"]').value !== 'unsure') throw new Error('Imported take lost experience');
    if (!document.querySelector('.status-pill').textContent.includes('準備完了')) throw new Error('Take import started playback');
    const wrongTakeTransfer = new DataTransfer();
    wrongTakeTransfer.items.add(new File([JSON.stringify({...restoredTake, scoreContext:'score-v1:wrong'})], 'wrong-take.json', {type:'application/json'}));
    await wait(() => !takeUpload.disabled, 'take import completes');
    takeUpload.files = wrongTakeTransfer.files;
    takeUpload.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => [...document.querySelectorAll('[role="status"]')].some(node => node.textContent.includes('テイクと楽譜の演奏条件が違います')), 'different take score conditions rejected');
    if (document.querySelector('[aria-label="テイク 2 の練習メモ"]').value !== '息継ぎの後をもう一度試す') throw new Error('Rejected take changed previous notes');
    const durationTransfer = new DataTransfer();
    durationTransfer.items.add(new File(['<score-partwise><part-list><score-part id="C"><part-name>Clarinet</part-name></score-part></part-list><part id="C"><measure number="7"><attributes><divisions>2</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes><note><pitch><step>C</step><octave>4</octave></pitch><duration>9</duration></note></measure></part></score-partwise>'], 'duration-warning.musicxml', {type:'application/xml'}));
    const durationUpload = document.querySelector('[aria-label="MusicXMLで演奏する"]');
    durationUpload.files = durationTransfer.files;
    durationUpload.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => { const text = document.querySelector('[aria-label="MusicXMLの再生上の注意"]')?.textContent ?? ''; return text.includes('拍子より長い小節') && text.includes('Clarinet・小節 7'); }, 'overlong measure warning and location in WKWebView');
    if (!document.querySelector('[aria-label="MusicXMLの再生上の注意"]').textContent.includes('Clarinet・小節 7')) throw new Error('Overlong measure location missing');
    if (errors.length) throw new Error(errors.join('; '));
    webkit.messageHandlers.testResult.postMessage({passed:true, checks:['saved take import restores notes without autoplay', 'selected second voice is prominent and solely highlighted', 'four repeated harmonic audio notes with short gaps advance the score through microphone analysis', 'current-measure rejoin holds position during count-in and resumes', 'bundled React app', 'unbundled repertoire is unavailable with an explanation', 'CoreMIDI disconnection holds position and reconnect requires explicit resume', 'simulated microphone disconnection returns UI to reconnectable state', 'bundled attribution and software license pages', 'Mozart MusicXML import', 'audio sample decode', 'WKWebView score engraving', 'IndexedDB save and muted part restoration', 'practice file opens after injected storage failure without autoplay', 'score page', 'missing asset 404', 'Web Audio note scheduling', 'transport stop', 'native print operation produces one PDF page per score page', 'AudioContext suspension preserves position and explicit recovery resumes audio', 'MusicXML, saved and current practice native exports with byte-for-byte SHA256 verification'], midi: 'CoreMIDI virtual source → WK bridge → React note and CC11, disconnect/reconnect, running status verified; physical instrument not tested', listeningQuality: 'not evaluated'});
  } catch (error) { webkit.messageHandlers.testResult.postMessage({passed:false,error:String(error)}); }
})();
