void (async () => {
  const wait = async (read, description) => {
    webkit.messageHandlers.testResult.postMessage({progress:description});
    const deadline = performance.now() + 30000;
    while (performance.now() < deadline) { const value = read(); if (value) return value; await new Promise(resolve => setTimeout(resolve, 100)); }
    throw new Error(`Timed out: ${description}; ${JSON.stringify({ status:query('.status-pill')?.textContent, seat:query('[aria-label="奏者パート"]')?.value, notes:[...document.querySelectorAll('.printable-score [data-score-beat]')].slice(0,8).map(note => ({voice:note.dataset.scoreVoice, staff:note.dataset.scoreStaff, focused:note.dataset.scoreFocused, current:note.classList.contains('score-current-note')})) })}`);
  };
  const visible = element => !!element?.getClientRects().length && getComputedStyle(element).visibility !== 'hidden';
  const query = selector => [...document.querySelectorAll(selector)].find(visible);
  const buttons = () => [...document.querySelectorAll('button')].filter(visible);
  const click = async text => {
    (await wait(() => buttons().find(button => button.textContent === text && !button.disabled), text)).click();
    await new Promise(resolve => setTimeout(resolve, 0));
    const screen = { '設定': 'settings', '‹ マイ楽譜': 'library', '楽譜で練習': 'practice' }[text];
    if (screen) await wait(() => query('.studio-shell')?.dataset.screen === screen, screen + ' navigation');
  };
  const openDetails = async selector => {
    const details = await wait(() => query(selector), 'visible panel ' + selector);
    if (!details.open) details.querySelector('summary').click();
    await wait(() => details.open, 'expanded panel ' + selector);
  };
  const openExperience = async label => {
    const field = await wait(() => document.querySelector('[aria-label="' + label + '"]'), 'experience field');
    const details = field.closest('details');
    if (!details.open) {
      const summary = details.querySelector('summary');
      if (!visible(summary)) throw new Error('Experience summary is hidden');
      summary.click();
    }
    await wait(() => visible(field), 'visible experience field');
    return field;
  };
  try {
    await wait(() => {
      const language = query('.language-switcher');
      if (!language) return false;
      if (document.documentElement.lang === 'ja' && language.value === 'ja') return true;
      language.value = 'ja';
      language.dispatchEvent(new Event('change', { bubbles: true }));
      return false;
    }, 'Japanese UI fixture');
    const errors = [];
    for (const style of ['400 16px Inter','italic 700 16px Inter']) {
      const fonts=await document.fonts.load(style,'ConvoCerto');
      if (!fonts.length || fonts.some(font=>font.status!=='loaded')) throw new Error('Bundled Inter font failed to load');
    }
    const fontResponse=await fetch('/fonts/inter/InterVariable.woff2');
    if (!fontResponse.ok || !fontResponse.headers.get('content-type')?.includes('font/woff2')) throw new Error('Native font MIME type missing');
    for (const [path, expected] of [['/credits.html', 'Frank Wen'], ['/notices/dependencies.html', 'Permission is hereby granted']]) {
      const resource = await fetch(path);
      if (!resource.ok || !resource.headers.get('content-type')?.includes('text/html') || !(await resource.text()).includes(expected)) throw new Error('Bundled notices missing: ' + path);
    }
    const bundledNotices = await (await fetch('/notices/bundled-packages.json')).json();
    if (!bundledNotices.packages.some(item => item.name === 'react' && item.noticeStatus === 'text-collected') || bundledNotices.commercialClearance !== false) throw new Error('Bundled package audit missing');
    let printResult;
    addEventListener("convocerto-print", event => { printResult = event.detail; });
    let sourceStarts = 0;
    let loopedStarts = 0;
    let playbackContext;
    const start = AudioBufferSourceNode.prototype.start;
    AudioBufferSourceNode.prototype.start = function (...args) { sourceStarts++; if (this.loop) loopedStarts++; playbackContext = this.context; return start.apply(this, args); };
    addEventListener('error', event => errors.push(event.message));
    const input = await wait(() => query('input[accept*=".mxl"]'), 'React input');
    await wait(() => query('[aria-label="はじめの2曲"]'), 'starter repertoire');
    if ([...document.querySelectorAll('.starter-scores button')].filter(visible).length !== 2) throw new Error('Starter library must offer exactly two scores');
    const catalogue = await (await fetch('/repertoire/ensemble/catalog.json')).json();
    if (catalogue.length !== 1 || catalogue[0].id !== 'mozart-k622-2') throw new Error('Distribution catalogue contains unbundled scores');
    for (const path of ['/repertoire/ensemble/mozart-k622-1.musicxml', '/repertoire/ensemble/ConvoCerto-MusicXML.zip', '/repertoire/mozart-k622-2.json']) if ((await fetch(path)).status !== 404) throw new Error('Non-starter asset entered native app: ' + path);
    const libraryResponse = await fetch('/repertoire/library/catalog.json');
    const library = await libraryResponse.json();
    if (!libraryResponse.ok || library.version !== 1 || library.scores.length !== 49 || library.scores.some(score => ['mozart-k622-2', 'bach-orchestral-suite-1', 'mozart-k581-clarinet-quintet'].includes(score.id))) throw new Error('Additional score library is incomplete or contains a held edition');
    const brass = library.scores.find(score => score.id === 'corelli-sarabande-brass-ensemble');
    const brassResponse = await fetch('/repertoire/library/' + brass.file);
    if (!brassResponse.ok || !brassResponse.headers.get('content-type')?.includes('application/vnd.recordare.musicxml')) throw new Error('Native MXL response is invalid');
    await openDetails('.repertoire-drawer');
    const brassButton = await wait(() => query('[data-score-id="corelli-sarabande-brass-ensemble"] button'), 'compressed brass score action');
    brassButton.click();
    await wait(() => query('.printable-score [data-score-beat]') && buttons().find(button => button.textContent === 'このパートで練習' && !button.disabled), 'compressed score engraving');
    if (sourceStarts) throw new Error('Catalogue score started without an explicit playback action');
    await click('♫ お手本');
    await wait(() => sourceStarts > 0 && Number(query('[aria-label="演奏位置"]').value) > 0, 'compressed score listening playback');
    await click('■ 試聴を止める');
    await click('‹ マイ楽譜');
    sourceStarts = 0;
    const response = await fetch('/repertoire/ensemble/mozart-k622-2.musicxml');
    if (!response.ok) throw new Error('Bundled Mozart missing');
    const xml = await response.text();
    const transfer = new DataTransfer();
    transfer.items.add(new File([xml], 'mozart.musicxml', {type:'application/xml'}));
    input.files = transfer.files; input.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => buttons().find(button => button.textContent === '▶ 演奏する' && !button.disabled), 'score and instrument samples');
    await wait(() => query('.printable-score svg'), 'engraved score');
    await click('このパートで練習');
    if ([...document.querySelectorAll('.studio-toolbar button')].filter(visible).length !== 6) throw new Error('Simple practice toolbar must expose exactly six controls');
    await wait(() => !query('.studio-tool-panel'), 'initial setup closes');
    await click('設定');
    query('.part-row button').click();
    await wait(() => query('.part-row button').getAttribute('aria-pressed') === 'true', 'mute accompaniment');
    await click('この練習を保存');
    await wait(() => query('.practice-save')?.textContent.includes('この練習を保存しました'), 'IndexedDB persistence');
    query('.part-row button').click();
    await wait(() => query('.part-row button').getAttribute('aria-pressed') === 'false', 'unmute before restore');
    await click('‹ マイ楽譜');
    const savedScore = await wait(() => query('[aria-label="マイ楽譜"] button[aria-label$="をマイ楽譜から削除"]'), 'visible saved score');
    savedScore.parentElement.querySelector('button').click();
    await wait(() => buttons().find(button => button.textContent === '▶ 演奏する' && !button.disabled), 'restored score view');
    await click('設定');
    await wait(() => query('.part-row button')?.getAttribute('aria-pressed') === 'true', 'restore saved mute');
    await wait(() => buttons().find(button => button.textContent === '▶ 演奏開始' && !button.disabled), 'restored instruments');
    if ((await fetch('/not-a-real-file.musicxml')).status !== 404) throw new Error('Missing asset must be 404');
    buttons().find(button => button.textContent === '▶ 演奏開始').click();
    await wait(() => Number(query('[aria-label="演奏位置"]').value) > 0 && sourceStarts > 0, 'Web Audio playback');
    buttons().find(button => button.textContent === 'この小節から入り直す').click();
    await wait(() => query('.status-pill')?.textContent.includes('カウントイン'), 'rejoin count-in');
    const rejoinBeat = Number(query('[aria-label="演奏位置"]').value);
    await new Promise(resolve => setTimeout(resolve, 300));
    if (Number(query('[aria-label="演奏位置"]').value) !== rejoinBeat) throw new Error('Rejoin advanced during count-in');
    await wait(() => Number(query('[aria-label="演奏位置"]').value) > rejoinBeat, 'rejoin transport after count-in');
    buttons().find(button => button.textContent === '■ 停止').click();
    const countInSelector = await wait(() => { const select = query('[aria-label="カウントイン"]'); return select && !select.disabled ? select : null; }, 'count-in selector after stop');
    countInSelector.value = '0'; countInSelector.dispatchEvent(new Event('change', {bubbles:true}));
    buttons().find(button => button.textContent === '▶ 演奏開始').click();
    await wait(() => Number(query('[aria-label="演奏位置"]').value) > 0, 'transport after rejoin verification');
    await playbackContext.suspend();
    const recover = await wait(() => buttons().find(button => button.textContent === '音声を復旧して再開'), 'audio interruption notice');
    const heldBeat = Number(query('[aria-label="演奏位置"]').value);
    await playbackContext.resume();
    await new Promise(resolve => setTimeout(resolve, 300));
    if (Number(query('[aria-label="演奏位置"]').value) !== heldBeat) throw new Error('Interrupted transport resumed without user action');
    await playbackContext.suspend();
    const startsBeforeRecovery = sourceStarts;
    recover.click();
    await wait(() => Number(query('[aria-label="演奏位置"]').value) > heldBeat && sourceStarts > startsBeforeRecovery, 'audio and transport recovery');
    const frozenClock = playbackContext.currentTime;
    Object.defineProperty(playbackContext,'currentTime',{configurable:true,get:()=>frozenClock});
    const clockRecovery = await wait(()=>buttons().find(button=>button.textContent==='音声を復旧して再開'),'frozen running audio clock recovery');
    const frozenBeat = Number(query('[aria-label="演奏位置"]').value);
    delete playbackContext.currentTime;
    await new Promise(resolve=>setTimeout(resolve,300));
    if (Number(query('[aria-label="演奏位置"]').value)!==frozenBeat) throw new Error('Frozen clock recovery autoplayed');
    clockRecovery.click();
    await wait(()=>Number(query('[aria-label="演奏位置"]').value)>frozenBeat,'explicit frozen clock resume');
    buttons().find(button => button.textContent === '■ 停止').click();
    if (Number(query('[aria-label="演奏位置"]').value) !== 0) await wait(() => Number(query('[aria-label="演奏位置"]').value) === 0, 'stop');
    await click('楽譜で練習');
    await wait(() => query('.printable-score svg'), 'visible score before print');
    await openDetails('.score-view-menu');
    const printedPages = document.querySelectorAll('.printable-score svg').length;
    buttons().find(button => button.textContent === '楽譜を印刷 / PDF').click();
    await wait(() => printResult, 'native print operation');
    if (printResult.status !== 'completed' || printResult.pages !== printedPages) throw new Error('Native print failed: ' + JSON.stringify({printResult,printedPages}));
    await click('設定');
    buttons().find(button => button.textContent === 'ClariMate / MIDIを接続').click();
    const deviceSelector = query('[aria-label="MIDI機器"]');
    const chooseTest = async () => {
      const option = await wait(() => [...deviceSelector.options].filter(option => option.textContent.includes('ConvoCerto Test Input')).at(-1), 'CoreMIDI test source');
      deviceSelector.value = option.value; deviceSelector.dispatchEvent(new Event('change', {bubbles:true}));
      return option.value;
    };
    const firstID = await chooseTest();
    const monitorButton = () => buttons().find(button => button.textContent.startsWith('MIDI入力の試聴（電子音）'));
    monitorButton().click();
    await wait(() => monitorButton().getAttribute('aria-pressed') === 'true', 'MIDI monitor audio ready');
    webkit.messageHandlers.convoMIDI.postMessage({action:'test-send',data:[0x90,72,85,0xb0,11,96]});
    await wait(() => query('.midi-reading').textContent.includes('強さ 85'), 'CoreMIDI note to React');
    await wait(() => query('[aria-label="ClariMateの息"]').value === 96, 'CoreMIDI CC11');
    const originalGainRamp = AudioParam.prototype.linearRampToValueAtTime;
    const monitorRamps = [];
    AudioParam.prototype.linearRampToValueAtTime = function (value, time) { monitorRamps.push(value); return originalGainRamp.call(this, value, time); };
    try {
      webkit.messageHandlers.convoMIDI.postMessage({action:'test-send',data:[0xb0,11,32]});
      await wait(() => monitorRamps.some(value => Math.abs(value - 32 / 127) < 0.0001), 'CoreMIDI expression changes monitor gain');
      monitorRamps.length = 0;
      webkit.messageHandlers.convoMIDI.postMessage({action:'test-send',data:[0xb0,2,0]});
      await wait(() => monitorRamps.includes(0), 'CoreMIDI zero breath silences monitor gain');
    } finally { AudioParam.prototype.linearRampToValueAtTime = originalGainRamp; }
    monitorButton().click();
    await wait(() => monitorButton().getAttribute('aria-pressed') === 'false', 'MIDI monitor stopped');
    buttons().find(button => button.textContent === '▶ 演奏開始').click();
    await wait(() => Number(query('[aria-label="演奏位置"]').value) > 0, 'transport before MIDI disconnect');
    webkit.messageHandlers.convoMIDI.postMessage({action:'test-disconnect'});
    await wait(() => ![...deviceSelector.options].some(option => option.value === firstID) && deviceSelector.value === '', 'device disconnection');
    await wait(() => !buttons().some(button => button.textContent === '■ 停止'), 'MIDI disconnection pauses transport');
    const midiHeldBeat = Number(query('[aria-label="演奏位置"]').value);
    if (midiHeldBeat <= 0) throw new Error('MIDI disconnection lost position');
    webkit.messageHandlers.convoMIDI.postMessage({action:'test-reconnect'});
    await chooseTest();
    webkit.messageHandlers.convoMIDI.postMessage({action:'test-send',packets:[[0x90,60],[71,0xf8,61,72]]});
    await wait(() => query('.midi-reading').textContent.includes('強さ 72'), 'reconnection and running status');
    if (Number(query('[aria-label="演奏位置"]').value) !== midiHeldBeat) throw new Error('MIDI reconnect resumed automatically');
    buttons().find(button => button.textContent === '▶ 演奏開始').click();
    await wait(() => Number(query('[aria-label="演奏位置"]').value) > midiHeldBeat, 'resume after MIDI reconnect');
    buttons().find(button => button.textContent === '■ 停止').click();
    const downloads = [];
    addEventListener('convocerto-download', event => downloads.push(event.detail));
    let exportedBlob;
    const objectURL = URL.createObjectURL;
    URL.createObjectURL = function (blob) { exportedBlob = blob; return objectURL.call(this, blob); };
    const verifyExport = async (label, filename) => {
      const before = downloads.length;
      const button = buttons().find(button => button.textContent === label);
      if (!button) throw new Error(`Missing export: ${label}`);
      button.click();
      const bytes = await exportedBlob.arrayBuffer();
      const digest = [...new Uint8Array(await crypto.subtle.digest('SHA-256', bytes))].map(byte => byte.toString(16).padStart(2,'0')).join('');
      const result = await wait(() => downloads[before], 'native file export');
      if (result.status !== 'saved' || result.sha256 !== digest || result.name !== filename) throw new Error(`Export mismatch: ${JSON.stringify(result)}`);
      return new TextDecoder().decode(bytes);
    };
    await openDetails('[aria-label="リハーサル設計"]');
    const exportedXML = await verifyExport('指示付きMusicXMLを保存', 'rehearsal.musicxml');
    if (!exportedXML.includes('score-partwise')) throw new Error('Exported XML has no score');
    const currentPractice = await verifyExport('今の練習をファイルに書き出す', 'practice.convo.json');
    if (JSON.parse(currentPractice).score.session.mutedPartIds?.length !== 1) throw new Error('Current practice export lost mute');
    await click('‹ マイ楽譜');
    await openDetails('[aria-label="マイ楽譜"]');
    const exportedPractice = await verifyExport('練習ファイルを書き出す', 'practice.convo.json');
    if (JSON.parse(exportedPractice).score.session.mutedPartIds?.length !== 1) throw new Error('Exported practice lost mute');
    if (JSON.parse(exportedPractice).format !== 'convocerto-practice') throw new Error('Practice envelope missing');
    const originalOpen = IDBFactory.prototype.open;
    try {
      IDBFactory.prototype.open = function (name, ...args) {
        if (name === 'convocerto-library') throw new DOMException('Test storage unavailable', 'SecurityError');
        return originalOpen.call(this, name, ...args);
      };
      const practiceTransfer = new DataTransfer();
      practiceTransfer.items.add(new File([currentPractice], 'backup.convo.json', {type:'application/json'}));
      const practiceInput = query('input[aria-label="練習ファイルを読み込む"]');
      practiceInput.files = practiceTransfer.files; practiceInput.dispatchEvent(new Event('change', {bubbles:true}));
      const openUnsaved = await wait(() => buttons().find(button => button.textContent === '保存せず、この練習を開く'), 'storage-independent practice import');
      openUnsaved.click();
      await wait(() => buttons().find(button => button.textContent === '▶ 演奏する' && !button.disabled), 'unsaved practice ready');
      await click('設定');
      await wait(() => query('.part-row button')?.getAttribute('aria-pressed') === 'true', 'unsaved practice mute');
      if (buttons().some(button => button.textContent === '■ 停止')) throw new Error('Unsaved practice started automatically');
    } finally { IDBFactory.prototype.open = originalOpen; }
    const originalMicrophone = navigator.mediaDevices.getUserMedia;
    const originalMicrophoneList = navigator.mediaDevices.enumerateDevices;
    let simulatedMicrophone;
    let simulatedTrack;
    try {
      const repeatedXML = `<score-partwise version="4.0"><work><work-title>Repeated microphone notes</work-title></work><part-list><score-part id="P1"><part-name>Clarinet</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>${Array.from({length:4}, () => '<note><pitch><step>A</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type><notations><fermata/></notations></note>').join('')}</measure></part></score-partwise>`;
      const repeatedTransfer = new DataTransfer();
      repeatedTransfer.items.add(new File([repeatedXML], 'repeated.musicxml', {type:'application/xml'}));
      await click('‹ マイ楽譜');
      const repeatedInput = query('input[accept*=".mxl"]');
      repeatedInput.files = repeatedTransfer.files; repeatedInput.dispatchEvent(new Event('change', {bubbles:true}));
      await wait(() => query('.performance-navigation')?.textContent.includes('Repeated microphone notes') && buttons().some(button => button.textContent === '▶ 演奏する' && !button.disabled), 'repeated-note score ready');
      await click('このパートで練習');
      await openDetails('[aria-label="MusicXMLの再生上の注意"]');
      if (!query('.playback-issues')?.textContent.includes('フェルマータ · 4件')) throw new Error('MusicXML playback limitations missing');
      await click('設定');
      const repeatedMode = query('[aria-label="練習モード"]');
      repeatedMode.value = 'wait'; repeatedMode.dispatchEvent(new Event('change', {bubbles:true}));
      let repeatedSource;
      navigator.mediaDevices.enumerateDevices = async () => [{kind:'audioinput', deviceId:'native-test-mic', label:'Native Test Microphone'}];
      buttons().find(button => button.textContent === 'マイク一覧を更新').click();
      await wait(() => query('[aria-label="使用するマイク"]')?.querySelector('option[value="native-test-mic"]'), 'microphone device list');
      const microphoneSelector = query('[aria-label="使用するマイク"]');
      microphoneSelector.value = 'native-test-mic'; microphoneSelector.dispatchEvent(new Event('change', {bubbles:true}));
      navigator.mediaDevices.getUserMedia = async (constraints) => {
        if (constraints.audio.deviceId?.exact !== 'native-test-mic') throw new Error('Selected microphone constraint missing');
        simulatedMicrophone = new AudioContext(); await simulatedMicrophone.resume();
        const destination = simulatedMicrophone.createMediaStreamDestination();
        repeatedSource = simulatedMicrophone.createBufferSource();
        const buffer = simulatedMicrophone.createBuffer(1, Math.ceil(simulatedMicrophone.sampleRate * 1.2), simulatedMicrophone.sampleRate);
        const samples = buffer.getChannelData(0);
        for (let i = 0; i < samples.length; i++) {
          const seconds = i / simulatedMicrophone.sampleRate;
          const phase = 2 * Math.PI * 440 * seconds;
          samples[i] = seconds % 0.3 < 0.26 ? 0.2 * Math.sin(phase) + 0.08 * Math.sin(3 * phase) : 0;
        }
        repeatedSource.buffer = buffer; repeatedSource.connect(destination);
        simulatedTrack = destination.stream.getAudioTracks()[0];
        Object.defineProperty(simulatedTrack, 'label', {value:'Native Test Microphone'});
        return destination.stream;
      };
      buttons().find(button => button.textContent === 'マイクで演奏する').click();
      await wait(() => buttons().find(button => button.textContent === 'マイクを停止'), 'simulated microphone connected');
      if (!microphoneSelector.disabled || !document.body.textContent.includes('使用中のマイク: Native Test Microphone')) throw new Error('Active microphone selection or label incorrect');
      buttons().find(button => button.textContent === '▶ 演奏開始').click();
      await wait(() => query('.status-pill')?.textContent === '正しい音を待っています', 'waiting for repeated microphone notes');
      repeatedSource.start();
      await wait(() => query('.status-pill')?.textContent === '演奏終了', 'four repeated microphone notes advance the score');
      if (Number(query('[aria-label="演奏位置"]').value) !== 4) throw new Error('Repeated microphone notes lost score position');
      simulatedTrack.stop(); simulatedTrack.dispatchEvent(new Event('ended'));
      await wait(() => [...document.querySelectorAll('[role="alert"]')].some(node => node.textContent.includes('マイク入力が中断しました')), 'microphone disconnection notice');
      if (!buttons().some(button => button.textContent === 'マイクで演奏する')) throw new Error('Microphone did not return to disconnected state');
      if (microphoneSelector.disabled || microphoneSelector.value !== 'native-test-mic' || document.body.textContent.includes('使用中のマイク:')) throw new Error('Disconnected microphone selection was not retained');
    } finally { navigator.mediaDevices.getUserMedia = originalMicrophone; navigator.mediaDevices.enumerateDevices = originalMicrophoneList; if (simulatedMicrophone) await simulatedMicrophone.close(); }
    const voiceXML = `<score-partwise version="4.0"><work><work-title>Selected voice display</work-title></work><part-list><score-part id="C"><part-name>Clarinets</part-name></score-part></part-list><part id="C"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes><note><pitch><step>C</step><octave>4</octave></pitch><duration>4</duration><voice>1</voice><type>whole</type></note><backup><duration>4</duration></backup><note><pitch><step>G</step><octave>4</octave></pitch><duration>4</duration><voice>2</voice><type>whole</type></note></measure></part></score-partwise>`.replace('<note>', '<direction><direction-type><dynamics><p/></dynamics><wedge type="crescendo"/></direction-type></direction><note>').replace('</measure>', '<direction><direction-type><wedge type="stop"/><dynamics><f/></dynamics></direction-type></direction></measure>').replaceAll('<duration>4</duration>', '<duration>8</duration>');
    const voiceTransfer = new DataTransfer();
    voiceTransfer.items.add(new File([voiceXML], 'voices.musicxml', {type:'application/xml'}));
    await click('‹ マイ楽譜');
    const voiceInput = query('input[accept*=".mxl"]');
    voiceInput.files = voiceTransfer.files; voiceInput.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => document.body.textContent.includes('Selected voice display') && !query('[aria-label="奏者パート"]').disabled, 'voice score ready');
    const voiceSelector = query('[aria-label="奏者パート"]');
    voiceSelector.value = JSON.stringify(['C', '1', '2']); voiceSelector.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => query('.printable-score [data-score-voice="2"][data-score-focused="true"]') && query('.printable-score [data-score-voice="1"][opacity="0.35"]') && query('.score-current-note[data-score-voice="2"]'), 'selected voice prominence');
    await click('このパートで練習');
    if (document.querySelectorAll('.score-current-note').length !== 1 || query('.score-current-note').dataset.scoreVoice !== '2') throw new Error('Highlight includes another player voice');
    if (query('.playback-issues')?.textContent.includes('フェルマータ')) throw new Error('Old MusicXML limitations persisted after another score loaded');
    const loopedBeforeHeldNote = loopedStarts;
    const hairpinRamps = new Map();
    const originalHairpinRamp = AudioParam.prototype.linearRampToValueAtTime;
    AudioParam.prototype.linearRampToValueAtTime = function(value,time) { const events=hairpinRamps.get(this) ?? []; events.push({value,time}); hairpinRamps.set(this,events); return originalHairpinRamp.call(this,value,time); };
    try {
      buttons().find(button=>button.textContent==='▶ 演奏する').click();
      await wait(()=>[...hairpinRamps.values()].some(events=>{const positive=events.filter(event=>event.value>0);return positive.length>1 && positive[1].value>positive[0].value*1.5 && positive[1].time-positive[0].time>0.3;}),'MusicXML hairpin schedules increasing sustained gain');
      if (loopedStarts <= loopedBeforeHeldNote) throw new Error('Long clarinet accompaniment did not use sustain loop');
      const beforeHeldSeek = sourceStarts;
      const heldSeek = query('[aria-label="演奏位置"]');
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(heldSeek,'2');
      heldSeek.dispatchEvent(new Event('input',{bubbles:true}));
      heldSeek.dispatchEvent(new Event('change',{bubbles:true}));
      await wait(()=>sourceStarts>beforeHeldSeek,'held orchestra note resumes after seeking inside note');
      buttons().find(button=>button.textContent==='■ 停止')?.click();
    } finally {AudioParam.prototype.linearRampToValueAtTime=originalHairpinRamp;}
    await click('設定');
    await openDetails('[aria-label="共奏のチューニング"]');
    const startTake = await wait(()=>buttons().find(button=>button.textContent==='テイクを記録して演奏' && !button.disabled),'take controls ready after stopping');
    startTake.click();
    const endTake = await wait(()=>buttons().find(button=>button.textContent==='テイクを終了'),'take recording available');
    endTake.click();
    const reuse = await openExperience('テイク 1 の再利用意向');
    if (reuse.value !== '') throw new Error('Experience answer must not be preselected');
    reuse.value='unsure'; reuse.dispatchEvent(new Event('change',{bubbles:true}));
    const memo=query('[aria-label="テイク 1 の練習メモ"]');
    Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(memo,'息継ぎの後をもう一度試す');
    memo.dispatchEvent(new Event('input',{bubbles:true}));
    await wait(()=>query('[aria-label="テイク 1 の再利用意向"]').value==='unsure' && query('[aria-label="テイク 1 の練習メモ"]').value==='息継ぎの後をもう一度試す','take experience retained during form editing');
    let takeBlob;
    const createTakeURL = URL.createObjectURL;
    const clickTakeLink = HTMLAnchorElement.prototype.click;
    try {
      URL.createObjectURL = function(blob) { takeBlob = blob; return createTakeURL.call(this, blob); };
      HTMLAnchorElement.prototype.click = function() { if (!this.download.startsWith('convo-take-')) clickTakeLink.call(this); };
      buttons().find(button => button.textContent === 'テイクの記録を保存').click();
    } finally { URL.createObjectURL = createTakeURL; HTMLAnchorElement.prototype.click = clickTakeLink; }
    if (!takeBlob) throw new Error('Take export missing');
    const restoredTake = JSON.parse(await takeBlob.text());
    restoredTake.id = 'native-restored-take';
    const takeUpload = query('[aria-label="保存したテイクを開く"]');
    const takeTransfer = new DataTransfer();
    takeTransfer.items.add(new File([JSON.stringify(restoredTake)], 'take.json', {type:'application/json'}));
    takeUpload.files = takeTransfer.files;
    takeUpload.dispatchEvent(new Event('change', {bubbles:true}));
    await openExperience('テイク 2 の練習メモ');
    await wait(() => query('[aria-label="テイク 2 の練習メモ"]')?.value === '息継ぎの後をもう一度試す', 'saved take import restores notes in WKWebView');
    if (query('[aria-label="テイク 2 の再利用意向"]').value !== 'unsure') throw new Error('Imported take lost experience');
    if (!query('.status-pill').textContent.includes('準備完了')) throw new Error('Take import started playback');
    const wrongTakeTransfer = new DataTransfer();
    wrongTakeTransfer.items.add(new File([JSON.stringify({...restoredTake, scoreContext:'score-v1:wrong'})], 'wrong-take.json', {type:'application/json'}));
    await wait(() => !takeUpload.disabled, 'take import completes');
    takeUpload.files = wrongTakeTransfer.files;
    takeUpload.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => [...document.querySelectorAll('[role="status"]')].some(node => node.textContent.includes('テイクと楽譜の演奏条件が違います')), 'different take score conditions rejected');
    if (query('[aria-label="テイク 2 の練習メモ"]').value !== '息継ぎの後をもう一度試す') throw new Error('Rejected take changed previous notes');
    await click('‹ マイ楽譜');
    await openDetails('.repertoire-drawer');
    const pianoSearch = await wait(() => query('.score-catalog [aria-label="曲を検索"]'), 'piano catalogue search');
    Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(pianoSearch, 'Schumann');
    pianoSearch.dispatchEvent(new Event('input', {bubbles:true}));
    const pianoScore = await wait(() => query('[data-score-id="library-58525"] .score-catalog-open'), 'compressed Schumann edition');
    const pianoStarts = sourceStarts;
    pianoScore.click();
    await wait(() => query('[aria-label="奏者パート"]')?.value === 'P1' && buttons().find(button => button.textContent === 'このパートで練習' && !button.disabled), 'Schumann whole-part selection');
    if (!query('.studio-part-options')?.textContent.includes('全体を担当すると、伴奏が残りません')) throw new Error('Whole piano part does not explain the missing accompaniment');
    await click('譜表1を担当');
    await wait(() => query('[aria-label="奏者パート"]')?.value === JSON.stringify(['P1', '1']) && query('.studio-part-picker')?.textContent.includes('このパートを伴奏から抜きます'), 'whole upper-staff seat with remaining accompaniment');
    await wait(() => ['1', '2', '3'].every(voice => query(`.printable-score [data-score-staff="1"][data-score-voice="${voice}"][data-score-focused="true"]`)) && query('.printable-score [data-score-staff="2"][data-score-focused="false"][opacity="0.35"]'), 'all upper-staff voices highlighted and lower staff dimmed');
    if (document.querySelector('.printable-score [data-score-staff="1"][data-score-focused="false"]')) throw new Error('A voice on the selected piano staff is dimmed');
    await click('このパートで練習');
    await wait(() => !query('.studio-tool-panel'), 'piano staff confirmation closes setup');
    if (sourceStarts !== pianoStarts || Number(query('[aria-label="演奏位置"]')?.value) !== 0 || buttons().some(button => button.textContent === '■ 停止')) throw new Error('Selecting or confirming a piano staff started playback');
    await click('↻ 区間');
    const pianoEntry = await wait(() => { const button = query('[aria-label="自分の入りの4小節"]'); return button && !button.disabled ? button : null; }, 'piano first-entry passage');
    pianoEntry.click();
    await wait(() => query('[aria-label="開始小節"]')?.value === '1' && query('[aria-label="終了小節"]')?.value === '4' && buttons().some(button => button.textContent === 'くり返し ON' && button.getAttribute('aria-pressed') === 'true'), 'piano first four bars selected');
    const pianoLeadIn = buttons().find(button => button.textContent === '入りの1小節前から');
    if (!pianoLeadIn?.disabled) throw new Error('First-bar piano entry incorrectly offers an earlier bar');
    await new Promise(resolve => setTimeout(resolve, 250));
    if (sourceStarts !== pianoStarts || Number(query('[aria-label="演奏位置"]')?.value) !== 0 || buttons().some(button => button.textContent === '■ 停止')) throw new Error('Selecting the first-entry passage started playback');
    await click('•••');
    await click('この練習を保存');
    const pianoSaved = await wait(() => { const status = query('.studio-save-action [role="status"]'); return status?.textContent === '保存しました' ? status : null; }, 'inline piano practice save confirmation');
    pianoSaved.scrollIntoView({block:'nearest'});
    await wait(() => { const box = pianoSaved.getBoundingClientRect(); return box.top >= 0 && box.bottom <= innerHeight && box.left >= 0 && box.right <= innerWidth; }, 'piano save confirmation within the visible window');
    const durationTransfer = new DataTransfer();
    durationTransfer.items.add(new File(['<score-partwise><part-list><score-part id="C"><part-name>Clarinet</part-name></score-part></part-list><part id="C"><measure number="7"><attributes><divisions>2</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes><note><pitch><step>C</step><octave>4</octave></pitch><duration>9</duration></note></measure></part></score-partwise>'], 'duration-warning.musicxml', {type:'application/xml'}));
    await click('‹ マイ楽譜');
    const durationUpload = query('[aria-label="MusicXMLで演奏する"]');
    durationUpload.files = durationTransfer.files;
    durationUpload.dispatchEvent(new Event('change', {bubbles:true}));
    await wait(() => { const text = query('[aria-label="MusicXMLの再生上の注意"]')?.textContent ?? ''; return text.includes('拍子より長い小節') && text.includes('Clarinet・小節 7'); }, 'overlong measure warning and location in WKWebView');
    await openDetails('[aria-label="MusicXMLの再生上の注意"]');
    if (!query('[aria-label="MusicXMLの再生上の注意"]').textContent.includes('Clarinet・小節 7')) throw new Error('Overlong measure location missing');
    if (errors.length) throw new Error(errors.join('; '));
    webkit.messageHandlers.testResult.postMessage({passed:true, checks:['visible navigation and expanded panels for every interaction', 'starter library has two scores and excludes full archive and fallback data', '49 additional compressed editions, native MXL MIME, brass notation and explicit listening playback', 'simple practice toolbar has six controls', 'saved take import restores notes without autoplay', 'selected second voice is prominent and solely highlighted', 'compressed Schumann whole-staff selection highlights all upper voices, retains accompaniment, selects the entry without autoplay and shows inline save feedback', 'four repeated harmonic audio notes with short gaps advance the score through microphone analysis', 'current-measure rejoin holds position during count-in and resumes', 'bundled React app', 'CoreMIDI disconnection holds position and reconnect requires explicit resume', 'simulated microphone disconnection returns UI to reconnectable state', 'bundled attribution and software license pages', 'Mozart MusicXML import', 'audio sample decode', 'WKWebView score engraving', 'IndexedDB save and muted part restoration', 'practice file opens after injected storage failure without autoplay', 'score page', 'missing asset 404', 'Web Audio note scheduling', 'transport stop', 'native print operation produces one PDF page per score page', 'AudioContext suspension preserves position and explicit recovery resumes audio', 'MusicXML, saved and current practice native exports with byte-for-byte SHA256 verification'], midi: 'CoreMIDI virtual source → WK bridge → React note and CC11, disconnect/reconnect, running status verified; physical instrument not tested', listeningQuality: 'not evaluated'});
  } catch (error) { webkit.messageHandlers.testResult.postMessage({passed:false,error:String(error)}); }
})();
