import { execFileSync } from 'node:child_process';
import { mkdirSync, cpSync, writeFileSync, existsSync, rmSync } from 'node:fs';
const app = 'build/native/ConvoCerto.app/Contents';
const minimumOS = '13.0';
const architecture = process.arch === 'arm64' ? 'arm64' : process.arch === 'x64' ? 'x86_64' : null;
if (process.platform !== 'darwin' || !architecture) throw new Error('Native build requires an arm64 or x86_64 Mac');
if (!existsSync('build/client/index.html')) throw new Error('Run npm run build first');
mkdirSync(`${app}/MacOS`, { recursive:true });
mkdirSync(`${app}/Resources`, { recursive:true });
execFileSync('swiftc', ['-target',`${architecture}-apple-macosx${minimumOS}`,'-swift-version','5','-O','native/ConvoCerto/LocalServer.swift','native/ConvoCerto/MIDIBytes.swift','native/ConvoCerto/MIDIBridge.swift','native/ConvoCerto/Downloads.swift','native/ConvoCerto/PrintBridge.swift','native/ConvoCerto/main.swift','-o',`${app}/MacOS/ConvoCerto`], {stdio:'inherit'});
rmSync(`${app}/Resources/web`, {recursive:true,force:true});
cpSync('build/client', `${app}/Resources/web`, {recursive:true});
cpSync('native/ConvoCerto/midi.js', `${app}/Resources/midi.js`);
cpSync('native/ConvoCerto/smoke.js', `${app}/Resources/smoke.js`);
cpSync('native/ConvoCerto/recovery-smoke.js', `${app}/Resources/recovery-smoke.js`);
cpSync('native/ConvoCerto/soak.js', `${app}/Resources/soak.js`);
writeFileSync(`${app}/Info.plist`, `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>CFBundleExecutable</key><string>ConvoCerto</string><key>CFBundleIdentifier</key><string>tech.gawatech.convocerto.preview</string><key>CFBundleName</key><string>ConvoCerto</string><key>CFBundlePackageType</key><string>APPL</string><key>LSMinimumSystemVersion</key><string>${minimumOS}</string><key>CFBundleVersion</key><string>1</string><key>CFBundleShortVersionString</key><string>0.1.0</string><key>NSMicrophoneUsageDescription</key><string>クラリネットの演奏に伴奏を合わせるためにマイクを使います。</string><key>NSCameraUsageDescription</key><string>演奏中のうなずきを合図として使います。</string><key>NSAppTransportSecurity</key><dict><key>NSAllowsLocalNetworking</key><true/></dict></dict></plist>`);
execFileSync('codesign', ['--force','--sign','-', 'build/native/ConvoCerto.app'], {stdio:'inherit'});
console.log('Built build/native/ConvoCerto.app (local development signature; not notarized)');
